name: skidkz_2
description: "SkidKZ 2.0"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  flutter_riverpod: ^2.6.1

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  local_auth: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  package_info_plus: ^9.0.0

  google_fonts: ^8.0.2
  intl: ^0.20.2

  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
